Update to 17.0.2
thisisthekap/Tonestro.Maui.FacebookSlim.Droid pull request #3
Opened 2024-10-25 14:14 UTC by albilaga

- Need to build with JDK 17
- Remove unneeded dependencies in Android project

2024-10-29 15:02 UTC, thisisthekap requested changes
Consider to upgrade CommunityToolkit.Maui.BindingExtensions to the most recent version

2024-10-30 08:35 UTC, albilaga commented
Updated @thisisthekap

2024-10-30 09:00 UTC, thisisthekap approved these changes

2024-10-30 09:00 UTC, thisisthekap commented
/azp run

2024-10-30 09:00 UTC, merged